name: Hola mundo

on: 
  workflow_dispatch: # ejecucion manual
  push: 
    branches: 
      - main
    paths: 
      - 'Biblioteca API/**'
      - 'BibliotecaAPITests/**'
      - '.github/workflows/main.yml'
  pull_request: 
    branches:
      - main

jobs:
  saludar: 
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "Hola mundo"

      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Listar los archivos del repositorio
        run: | 
          echo "El repositorio: ${{ github.repository }} contiene los siguientes archivos:"
          tree
